{
 "title": "Spring boot - push",
 "description": "Grafana Dashboard for Spring Boot App.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Requests total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (http_server_request_duration_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (http_route) (http_server_request_duration_seconds_count{http_route=\"/ping\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "General Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_server_request_duration_seconds_count[5m]))",
     "legendFormat": "request rate"
    }
   ]
  },
  {
   "title": "Network Input",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "rate(net_bytes_recv[5m])", "legendFormat": "net_bytes_recv" },
    {
     "expr": "rate(net_conntrack_listener_conn_accepted_total[5m])",
     "legendFormat": "net_conn_accepted"
    }
   ]
  }
 ]
}