apiVersion: batch/v1
kind: Job
metadata:
  generateName: kafka-strimzi-producer-
  namespace: kafka
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 1
  template:
    metadata:
      name: kafka-strimzi-producer
      labels:
        app: kafka-strimzi-producer
    spec:
      restartPolicy: Never
      containers:
      - name: kafka-strimzi-producer
        image: quay.io/zroubalik/kafka-app:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        command: [ "/kafkaproducerapp" ]
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap.kafka.svc:9092
          - name: TOPIC
            value: my-topic2
          - name: MESSAGE_COUNT
            value: "15"                    # increase this for a bigger load
          - name: DELAY_MS
            value: "100"
