kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
  namespace: kafka
spec:
  partitions: 5
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
---
kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: my-topic2
  labels:
    strimzi.io/cluster: my-cluster
  namespace: kafka
spec:
  partitions: 5
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824