kind: ScaledObject
apiVersion: keda.sh/v1alpha1
metadata:
  name: http-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-server
  cooldownPeriod: 5
  minReplicaCount: 0
  maxReplicaCount: 10
  fallback:                                       
    failureThreshold: 2           
    replicas: 1
  advanced:                                              
    restoreToOriginalReplicaCount: true            
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 5
  triggers:
  - type: kedify-http
    metadata:
      hosts: demo.keda
      service: http-server
      port: "8080"
      scalingMetric: requestRate
      targetValue: "10"
      granularity: 1s
      window: 10s