# This example demonstrates how to use the kedify-envoy-http trigger to scale a deployment based on the request rate
# https://kedify.io/documentation/scalers/http-envoy-scaler/
#
# Things to check:
# 
# 1. interceptor internal envoy metrics map is formed correctly
# $ kubectl get --raw /api/v1/namespaces/keda/services/keda-add-ons-http-interceptor-admin:9090/proxy/envoy-metrics-map
# {"default/test": "default/http-server"}
# 
# 2. envoy connected to the interceptor metrics sink and is sending metrics
# $ kubectl get --raw /api/v1/namespaces/keda/services/keda-add-ons-http-interceptor-metrics:2223/proxy/metrics | grep '^kedify'
# kedify_envoysink_metrics_cluster_name_ignored{envoy_cluster_name="kedify_metrics_service",envoy_ip="10.42.0.16",stream_id="396c8eaf-4b49-4c20-92ab-4a08cc8ab9a6"} 320
# kedify_envoysink_metrics_flushes_processed_total{envoy_ip="10.42.0.16",stream_id="396c8eaf-4b49-4c20-92ab-4a08cc8ab9a6"} 17440
# kedify_envoysink_metrics_sessions_current{envoy_ip="10.42.0.16",stream_id="396c8eaf-4b49-4c20-92ab-4a08cc8ab9a6"} 1
#
# 3. routing works correctly
# $ curl -I -H host:demo.keda http://$(kubectl get ingress -o json envoy | jq -r '.status.loadBalancer.ingress[].ip')
# HTTP/1.1 200 OK
# Content-Length: 320
# Content-Type: text/html
# Date: Wed, 12 Mar 2025 07:45:12 GMT
# Server: envoy
# X-Envoy-Upstream-Service-Time: 0
# 
# 4. metrics queue in the interceptor is operational
# $ kubectl get --raw /api/v1/namespaces/keda/services/keda-add-ons-http-interceptor-admin:9090/proxy/queue
# {"default/http-server":{"Concurrency":0,"RPS":0.041}}
#
# 5. check the scaling
# $ hey -z 5m -c 500 -q 500 -host demo.keda http://$(kubectl get ingress -o json envoy | jq -r '.status.loadBalancer.ingress[].ip')
# ...
# Status code distribution:
#   [200] 331208 responses
#
# $ kubectl get --raw /api/v1/namespaces/keda/services/keda-add-ons-http-interceptor-admin:9090/proxy/queue
# {"default/http-server":{"Concurrency":151,"RPS":12411.918}}
#
# $ kubectl get hpa keda-hpa-http-server
# NAME                   REFERENCE                TARGETS             MINPODS   MAXPODS   REPLICAS   AGE
# keda-hpa-http-server   Deployment/http-server   1215200m/10 (avg)   1         10        10         17m
#
# $ kubectl get --raw /api/v1/namespaces/keda/services/keda-add-ons-http-interceptor-metrics:2223/proxy/metrics | grep '^kedify'
# kedify_envoysink_metrics_cluster_name_ignored{envoy_cluster_name="kedify_metrics_service",envoy_ip="10.42.0.16",stream_id="396c8eaf-4b49-4c20-92ab-4a08cc8ab9a6"} 1324
# kedify_envoysink_metrics_concurrent_set_count{envoy_cluster_name="test",envoy_ip="10.42.0.16",stream_id="396c8eaf-4b49-4c20-92ab-4a08cc8ab9a6"} 442
# kedify_envoysink_metrics_concurrent_set_current{envoy_cluster_name="test",envoy_ip="10.42.0.16",stream_id="396c8eaf-4b49-4c20-92ab-4a08cc8ab9a6"} 83
# kedify_envoysink_metrics_concurrent_set_total{envoy_cluster_name="test",envoy_ip="10.42.0.16",stream_id="396c8eaf-4b49-4c20-92ab-4a08cc8ab9a6"} 31108
# kedify_envoysink_metrics_flushes_processed_total{envoy_ip="10.42.0.16",stream_id="396c8eaf-4b49-4c20-92ab-4a08cc8ab9a6"} 104571
# kedify_envoysink_metrics_rps_set_count{envoy_cluster_name="test",envoy_ip="10.42.0.16",stream_id="396c8eaf-4b49-4c20-92ab-4a08cc8ab9a6"} 161
# kedify_envoysink_metrics_rps_set_current{envoy_cluster_name="test",envoy_ip="10.42.0.16",stream_id="396c8eaf-4b49-4c20-92ab-4a08cc8ab9a6"} 13371
# kedify_envoysink_metrics_rps_set_total{envoy_cluster_name="test",envoy_ip="10.42.0.16",stream_id="396c8eaf-4b49-4c20-92ab-4a08cc8ab9a6"} 1.943328e+06
# kedify_envoysink_metrics_rps_zero_value_count{envoy_cluster_name="test",envoy_ip="10.42.0.16",stream_id="396c8eaf-4b49-4c20-92ab-4a08cc8ab9a6"} 281
# kedify_envoysink_metrics_sessions_current{envoy_ip="10.42.0.16",stream_id="396c8eaf-4b49-4c20-92ab-4a08cc8ab9a6"} 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
        - name: http-server
          image: ghcr.io/kedify/sample-http-server:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: RESPONSE_DELAY
              value: "0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: http-server
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: http
  selector:
    app: http-server
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-server
  cooldownPeriod: 5
  minReplicaCount: 1
  maxReplicaCount: 10
  fallback:                                       
    failureThreshold: 2           
    replicas: 1
  advanced:                                              
    restoreToOriginalReplicaCount: true            
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 5
  triggers:
  - type: kedify-envoy-http
    metadata:
      scalingMetric: requestRate
      targetValue: "10"
      externalProxyMetricKey: "test"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
      - args:
        - --config-yaml
        - $(ENVOY_CONFIG)
        env:
        - name: ENVOY_CONFIG
          value: |-
            stats_flush_interval: 1s
            stats_sinks:
            - name: kedify_metrics_sink
              typed_config:
                "@type": type.googleapis.com/envoy.config.metrics.v3.MetricsServiceConfig
                transport_api_version: V3
                report_counters_as_deltas: true
                emit_tags_as_labels: true
                grpc_service:
                  envoy_grpc:
                    cluster_name: kedify_metrics_service
                  retry_policy:
                    retry_back_off:
                      base_interval: 0.5s
                      max_interval: 5s
                    num_retries: 100
                    retry_on: connect-failure
            node:
              id: kedify-proxy
              cluster: xds_cluster
            admin:
              address:
                socket_address:
                  address: 0.0.0.0
                  port_value: 9901
            static_resources:
              listeners:
              - name: listener_0
                address:
                  socket_address: { address: 0.0.0.0, port_value: 8080 }
                filter_chains:
                - filters:
                  - name: envoy.filters.network.http_connection_manager
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                      stat_prefix: ingress_http
                      codec_type: AUTO
                      route_config:
                        name: local_route
                        virtual_hosts:
                        - name: local_service
                          domains: ["*"]
                          routes:
                          - match:
                              prefix: "/"
                            route:
                              cluster: test
                              auto_host_rewrite: false
                      http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              clusters:
              - name: kedify_metrics_service
                connect_timeout: 2s
                type: STRICT_DNS
                lb_policy: ROUND_ROBIN
                typed_extension_protocol_options:
                  envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
                    "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
                    explicit_http_config:
                      http2_protocol_options: {}
                load_assignment:
                  cluster_name: kedify_metrics_service
                  endpoints:
                  - lb_endpoints:
                    - endpoint:
                        address:
                          socket_address:
                            address: "keda-add-ons-http-interceptor-kedify-proxy-metric-sink.keda.svc.cluster.local"
                            port_value: 9901
              - name: test
                connect_timeout: 10s
                type: STRICT_DNS
                lb_policy: ROUND_ROBIN
                load_assignment:
                  cluster_name: test
                  endpoints:
                  - lb_endpoints:
                    - endpoint:
                        address:
                          socket_address:
                            address: http-server
                            port_value: 8081
        image: envoyproxy/envoy:v1.33.0
        imagePullPolicy: IfNotPresent
        name: envoy
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: envoy
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
  selector:
    app: envoy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: envoy
spec:
  rules:
  - host: "demo.keda"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: envoy
              port:
                number: 8080
