---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
        - name: http-server
          image: ghcr.io/kedify/sample-http-server:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: RESPONSE_DELAY
              value: "0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: http-server
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: http
  selector:
    app: http-server
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-server
  cooldownPeriod: 5
  minReplicaCount: 1
  maxReplicaCount: 10
  fallback:                                       
    failureThreshold: 2           
    replicas: 1
  advanced:                                              
    restoreToOriginalReplicaCount: true            
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 5
  triggers:
  - type: kedify-envoy-http
    metadata:
      scalingMetric: requestRate
      targetValue: "10"
      externalProxyMetricKey: "test"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
      - args:
        - --config-yaml
        - $(ENVOY_CONFIG)
        env:
        - name: ENVOY_CONFIG
          value: |-
            stats_flush_interval: 1s
            stats_sinks:
            - name: kedify_metrics_sink
              typed_config:
                "@type": type.googleapis.com/envoy.config.metrics.v3.MetricsServiceConfig
                transport_api_version: V3
                report_counters_as_deltas: true
                emit_tags_as_labels: true
                grpc_service:
                  envoy_grpc:
                    cluster_name: kedify_metrics_service
                  retry_policy:
                    retry_back_off:
                      base_interval: 0.5s
                      max_interval: 5s
                    num_retries: 100
                    retry_on: connect-failure
            node:
              id: kedify-proxy
              cluster: xds_cluster
            admin:
              address:
                socket_address:
                  address: 0.0.0.0
                  port_value: 9901
            static_resources:
              listeners:
              - name: listener_0
                address:
                  socket_address: { address: 0.0.0.0, port_value: 8080 }
                filter_chains:
                - filters:
                  - name: envoy.filters.network.http_connection_manager
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                      stat_prefix: ingress_http
                      codec_type: AUTO
                      route_config:
                        name: local_route
                        virtual_hosts:
                        - name: local_service
                          domains: ["*"]
                          routes:
                          - match:
                              prefix: "/"
                            route:
                              cluster: test
                              auto_host_rewrite: false
                      http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              clusters:
              - name: kedify_metrics_service
                connect_timeout: 2s
                type: STRICT_DNS
                lb_policy: ROUND_ROBIN
                typed_extension_protocol_options:
                  envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
                    "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
                    explicit_http_config:
                      http2_protocol_options: {}
                load_assignment:
                  cluster_name: kedify_metrics_service
                  endpoints:
                  - lb_endpoints:
                    - endpoint:
                        address:
                          socket_address:
                            address: "keda-add-ons-http-interceptor-kedify-proxy-metric-sink.keda.svc.cluster.local"
                            port_value: 9901
              - name: test
                connect_timeout: 10s
                type: STRICT_DNS
                lb_policy: ROUND_ROBIN
                load_assignment:
                  cluster_name: test
                  endpoints:
                  - lb_endpoints:
                    - endpoint:
                        address:
                          socket_address:
                            address: http-server
                            port_value: 8081
        image: envoyproxy/envoy:v1.33.0
        imagePullPolicy: IfNotPresent
        name: envoy
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: envoy
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
  selector:
    app: envoy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: envoy
spec:
  rules:
  - host: "demo.keda"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: envoy
              port:
                number: 8080
