apiVersion: v1
kind: Secret
metadata:
  name: grpc-responder
data:
  tls.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lVUm9tc01hcSt4RVZLaXZFZmFUbGFNaGdmQVNRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZERVNNQkFHQTFVRUF3d0piRzlqWVd4b2IzTjBNQjRYRFRJME1EZ3hOakV6TURBd09Gb1hEVEkxTURneApOakV6TURBd09Gb3dGREVTTUJBR0ExVUVBd3dKYkc5allXeG9iM04wTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBc0EraGlndklOQWUyTjRyN3YvOEJlNGUxSjlhUDFmdElVamdRYVFlQW9CTUQKa0dKOFRYQ3cvRjR0NTVvQ1liMS9nWUEyckU5aXlsdlJDOUg4OEsxemdXa0RtSWc2VE9PMzJmMmp0S2pic2lSYwpkek16UVNzczR6aWduSE53eHZVQmN6bXV0RVcrWUlFWjhnTzBlSnFabzhpWEtLMHpRU2I2VG5zUTFLa0dUQTdLCkQzN1poTmF4by9saTRzVk4wdzlMOG5YZWdSUkNHSVpRdlp6c0JtZVBQYWlZK2dqdE1ZZmR3WW80N3o4ZThRZjQKR2FlYnQzbmhRUGdsNStpRi85VjBEQlIycThrUXN3cjlPYnlFRjBFUjdyRkp0dnJiaW5tOGR0QTFYYURWYVZINwpMU1NMdjRpVFU0WEJSZ2gzQm5BMXZCZEhTV3Y4THV5b2MxVTFhR2hUN3dJREFRQUJvMGd3UmpBbEJnTlZIUkVFCkhqQWNnZ2xzYjJOaGJHaHZjM1NDQ1dkeWNHTXVhMlZrWVljRWZ3QUFBVEFkQmdOVkhRNEVGZ1FVRjdOTVFjbTMKVGJMZkVpNWFIQXJPVTU0TE9LZ3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSC9RRkhDQ041QnBXditFQWpGeApWcGQ2KzdjZFJicU9kckxZR3VEc1ZCcnNqSjQ2SGZFdVVpT0p4RitmOVU2N2R3ck9HTklIRHVEYnFjenNlcEV6CnZ3UTM4WGhaWUZNZE9tbUY3UXlNL25KK08zUmRycEMzYWNTem81WkNMczg3UHNVdlF4VlRudW1rMjBnUGVQNEIKNkN2MEhaSzB6cnZhQm1McFNDR1VnWVpNdlBRZGtJcmw3UkxUSUR4S0s1ZEpIZUxLWitNZlJDZlUwa2xjN0thRwo0VEF6ZEc1R1Irb2F0MUZrNlREK1l6Y2xoV0FLdE9veFJDN1hwdkU4Y0ZweXNDUWdpUEd6T2l0TUxMcjQvSTBjCkp4L0pRN1ZwdjBIaHdjTVhnbGtXUjNOaVVnWDlaaEZqWDRJMUhvL0Z4bVZReVpOMzhvUFArWWF4MlhaRVdIU3kKQjljPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: >-
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQ3dENkdLQzhnMEI3WTMKaXZ1Ly93RjdoN1VuMW8vViswaFNPQkJwQjRDZ0V3T1FZbnhOY0xEOFhpM25tZ0podlgrQmdEYXNUMkxLVzlFTAowZnp3clhPQmFRT1lpRHBNNDdmWi9hTzBxTnV5SkZ4M016TkJLeXpqT0tDY2MzREc5UUZ6T2E2MFJiNWdnUm55CkE3UjRtcG1qeUpjb3JUTkJKdnBPZXhEVXFRWk1Ec29QZnRtRTFyR2orV0xpeFUzVEQwdnlkZDZCRkVJWWhsQzkKbk93R1o0ODlxSmo2Q08weGg5M0Jpamp2UHg3eEIvZ1pwNXUzZWVGQStDWG42SVgvMVhRTUZIYXJ5UkN6Q3YwNQp2SVFYUVJIdXNVbTIrdHVLZWJ4MjBEVmRvTlZwVWZzdEpJdS9pSk5UaGNGR0NIY0djRFc4RjBkSmEvd3U3S2h6ClZUVm9hRlB2QWdNQkFBRUNnZ0VBQWRMYVNxcVk2TWU1cTBxZEZVaUlGSkQ3eWVLdTVtUll3KzFCRWtMRWQzbFYKbkozQWlZYlBkb0JuNWxHOGtPbWNhVlFtMGlodEJBaytidXBwRXlSMklWTGIrWUpUdVpuVVBOcjVOL1VBZURzVApNQjJQZkM4bnpiUzNub0hvUmFTaVhyWUJhV3hJTHJTM29aVHpQaHFQMlMxSjVOOGladkdIUHpVeGRVVWVRNzhSCkJKcHlIZlJLWjB1NVlNdVRuemhEZXBVVjBVVEFxd2QrcnpWT1V2UzFRWkZkaFJ4S0dxQVY3eXVIU1FPVWNKcUoKaU54RGgrcHVtNlhaSENQVUs1TXcxUml2LzlGbjRjSktnMzVYSUh3a0d5eGdsaUZJVEQwTUZ0MGF6U2QxVmRDTQo2K2lGTE1WblM1cnlVWjhVcDlQdE1HNzRJcnVHamhVUEMwdFFXOXIxN1FLQmdRRDRYWGR4UENoSmNsWm5jYTE1CnRYLzExZFMzczd2clY0NmxyUHlQN1FMUnNjR2poTFhEZnc3QkZwdjlWR21LaXZWUm0zOWN0R0lvRllvYXZZTUIKTmRWZ0lRVG9qTTVIQk1VWktldDhuOHlYWVZQRHByYjVkcGlsTHRMb1loaVlKM1J5NzlFbWMweXg5b1hqZldZeApJTEdUTEpZT1JRelhWNzlGNUFpT3llSU9KUUtCZ1FDMWVTa2puNVF3S01vQzJlTFAydnFkUWJCR0tIU1ZjQU9uCnlHbDZHMlNJNWJ4djU2blJyQjNEb21XTGFYdVhlTi9nT3ZzSWMyekJIekNxTUNPb1ZsY3AvenFpM0VQL3ZDbEEKdWJOQkd4WDU5bFlDVWk4N1VpbC81dThvenE3Vnd1SDM4ZHlDYWg5Ujdma0xRM3lGQ1VuWkMwUHFQOFVMdUxhcgp4cW5kN2NtTGd3S0JnQ0V3ckdPUGZIckVNdFBFRjBDcWhwMGRwRDJnWVQ2RUJ1WVJCZmRkM3dDUzFxTzVlbWpUCnMrOE56RzdBTnhKeW0zSDZhN3pCeGxSQS9LR3lMYTJkdWhRTWxaRldMOExCMm0wUWN3M0dkUnJOd05ubWo1RXEKemg5VThJNXBmWXZueWVJS05sTURHWDYyeVJHcmtscUNXZmltL3E2TmY3ZlBYQnBFN1BmWDlzT1pBb0dBUHI3NQozbnRhdlp3YzNRZUJTT1VxS2gyQVdZRzdiY0FoUTI0a0tqZzJkcThZaklqSlN0bjhJSnlTQjdZZEthNTltZ1pLCnJnMWEyUnR6dENTWTc2ZUswOWFQNjZmRlN6TkFBRVUxR1puSDYzbWxHNEJYSEdlNE9hVWJwRHh5Ynk3Ryt2Z0IKaW9ZdTlpRVdMekxTWngxakQweTUydERaek1lOVFYK2JWRVRYbndrQ2dZQnlvZmxJTDM4QTR0YWRvZVZFd1NESwpoNk8wUklPa29Yc3NXeWZYZnlRamh5UmRHOTRPYTQvRGw4SkdYSzdYdmhQMTN1aC9yZ21EcnlWRjV1UFYzT3FHCjhYUWJ2TENZNUEreUlGTW9pb3pBcE9JdHRtbnRRaUg3dVluTmV4NEorWVJZWEttMzh1Wkg2RlRBRkxsYy84czEKVmhlY1JVakV5YXdkRlNEZHB1ajZ3Zz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
type: kubernetes.io/tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-responder
  labels:
    app: grpc-responder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-responder
  template:
    metadata:
      labels:
        app: grpc-responder
    spec:
      containers:
      - name: grpc-responder
        image: ghrc.io/kedify/sample-grpc-responder
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: RESPONSE_DELAY
          value: "0.5"
        - name: RESPONSE_MESSAGE
          value: "Hello from Kedify"
        - name: TLS_ENABLED
          value: "true"
        - name: TLS_CERT_FILE
          value: "/certs/tls.crt"
        - name: TLS_KEY_FILE
          value: "/certs/tls.key"
        volumeMounts:
        - name: certs
          mountPath: /certs
      volumes:
      - name: certs
        secret:
          secretName: grpc-responder
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-responder
spec:
  selector:
    app: grpc-responder
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
  type: ClusterIP