apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: my-app-be
  namespace: app
spec:
  scaleTargetRef:
    name: my-app-be-router
  triggers:
    - type: kubernetes-workload
      metadata:
        podSelector: 'app=my-app-fe'
        value: "1"
  minReplicaCount: 1
  maxReplicaCount: 4
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 120
        scaleUp:
          stabilizationWindowSeconds: 0
