apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: my-app-fe-so
  namespace: app
spec:
  scaleTargetRef:
    name: my-app-fe
  triggers:
    - type: kedify-otel
      metadata:
        scalerAddress: "keda-otel-scaler.keda.svc:4318"
        metricQuery: "sum(nginx_ingress_controller_connect_duration_seconds_count{service=my-app-fe,namespace=app})"
        operationOverTime: "rate"
        targetValue: "1000"
  minReplicaCount: 1
  maxReplicaCount: 4
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 0
