apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: websocket-server
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 5
    scalingModifiers: {}
  cooldownPeriod: 5
  maxReplicaCount: 2
  minReplicaCount: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: websocket-server
  triggers:
  - metadata:
      granularity: 1s
      hosts: websocket.keda
      pathPrefixes: /
      port: "8080"
      scalingMetric: requestRate
      service: websocket-server
      targetValue: "100"
      window: 1m
    metricType: AverageValue
    type: kedify-http
