settings:
  metricStore:
    retentionSeconds: 60
  logs:
    logLvl: debug

otelOperator:
  enabled: true
  # manager:
  #   extraArgs:
  #   - --zap-log-level=debug

otelOperatorCrs:
- name: otel-sidecar-template
  enabled: true
  debug: true
  mode: deployment
  namespace: default
  prometheusScrapeConfigs:
    - job_name: 'otel-collector'
      scrape_interval: 5s
      static_configs:
        - targets: [ 'vllm-router-service.default.svc:80' ]
  includeMetrics:
    - vllm:current_qps
    - vllm:num_requests_waiting
    - vllm:avg_latency