settings:
  metricStoreRetentionSeconds: 60
  # logs:
  #   logLvl: debug

opentelemetry-collector:
  clusterRole:
    create: true
    # additional rbac for upstream otel collector to be able to find pods w/ prometheus.io/scrape annotation
    # not needed, when only static targets are used
    rules:
     - apiGroups:
       - ''
       resources:
       - 'pods'
       verbs:
       - 'get'
       - 'list'
       - 'watch'
  alternateConfig:
    receivers:
      opencensus:
      
      # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/README.md
      prometheus:
        config:
          scrape_configs:
            - job_name: k8s
              scrape_interval: 5s
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                  regex: "true"
                  action: keep
                - source_labels: [__meta_kubernetes_pod_name]
                  action: replace
                  target_label: pod_name
    exporters:
      otlp:
        endpoint: keda-otel-scaler.keda.svc:4317
        #compression: "none"

    service:
      pipelines:
        metrics:
          receivers:
            - prometheus
          exporters:
            - otlp
