apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: work-simulator-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: work-simulator
  endpoints:
    - port: http
      path: /metrics
      interval: 5s