#!/usr/bin/env bash
set -euo pipefail

# generate-fleet.sh writes a single manifest file with N load-generator apps
# and N matching PodResourceAutoscalers. Schedules are set via SCHEDULE_JSON env.

usage() {
  cat <<'EOF'
Usage:
  ./scripts/generate-fleet.sh <count> [output-file]

Arguments:
  count        Number of load-generator apps and PRAs to generate.
  output-file  Optional output path (default: ./config/generated-fleet.yaml).

Environment:
  IMAGE                  Container image for load-generator
                         default: ghcr.io/kedify/sample-load-generator:latest
  LOOP_MODE              Schedule loop mode: mixed | once | loop
                         default: loop
  MIN_STEP_SECONDS       Minimum duration for each schedule step
                         default: 300 (values lower than 300 are clamped to 300)
  NAMESPACE              Optional namespace for generated resources
EOF
}

if [[ $# -lt 1 || $# -gt 2 ]]; then
  usage
  exit 1
fi

count="$1"
if ! [[ "$count" =~ ^[1-9][0-9]*$ ]]; then
  echo "error: count must be a positive integer" >&2
  exit 1
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
default_output="${script_dir}/../config/generated-fleet.yaml"
output="${2:-$default_output}"

image="${IMAGE:-ghcr.io/kedify/sample-load-generator:latest}"
loop_mode="${LOOP_MODE:-loop}"
min_step_seconds="${MIN_STEP_SECONDS:-300}"
namespace="${NAMESPACE:-}"

case "$loop_mode" in
  mixed | once | loop) ;;
  *)
    echo "error: LOOP_MODE must be one of: mixed, once, loop" >&2
    exit 1
    ;;
esac

if ! [[ "$min_step_seconds" =~ ^[0-9]+$ ]]; then
  echo "error: MIN_STEP_SECONDS must be a non-negative integer" >&2
  exit 1
fi
if (( min_step_seconds < 300 )); then
  min_step_seconds=300
fi

mkdir -p "$(dirname "$output")"

namespace_line=""
if [[ -n "$namespace" ]]; then
  namespace_line=$'\n  namespace: '"$namespace"
fi

schedule_payload=""

build_schedule_payload() {
  local idx="$1"

  # Alternate medium/high phases with idle phases so PRA keeps scaling up/down.
  # This avoids spike profile OOM risk when initial memory limit is 600Mi.
  local stress_profiles=(medium high)
  local p1="${stress_profiles[$(((idx - 1) % 2))]}"
  local p2="${stress_profiles[$((idx % 2))]}"

  local hot1=$((min_step_seconds + ((idx % 3) * 120)))
  local idle1=$((min_step_seconds + (((idx - 1) % 3) * 60)))
  local hot2=$((min_step_seconds + (((idx + 1) % 3) * 90)))
  local idle2=$((min_step_seconds + (((idx + 2) % 3) * 60)))

  local steps_json
  steps_json="$(printf '{"profile":"%s","durationSeconds":%d},{"profile":"idle","durationSeconds":%d},{"profile":"%s","durationSeconds":%d},{"profile":"idle","durationSeconds":%d}' "$p1" "$hot1" "$idle1" "$p2" "$hot2" "$idle2")"

  local loop_value=false
  case "$loop_mode" in
    once)
      loop_value=false
      ;;
    loop)
      loop_value=true
      ;;
    mixed)
      if (( idx % 2 == 1 )); then
        loop_value=true
      fi
      ;;
  esac

  schedule_payload="$(printf '{"loop":%s,"steps":[%s]}' "$loop_value" "$steps_json")"
}

cat >"$output" <<EOF
# Generated by scripts/generate-fleet.sh
# count: ${count}
# loop_mode: ${loop_mode}
# min_step_seconds: ${min_step_seconds}

EOF

for ((i = 1; i <= count; i++)); do
  printf -v suffix "%02d" "$i"
  app_name="load-generator-${suffix}"

  build_schedule_payload "$i"

  cat >>"$output" <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${app_name}${namespace_line}
  labels:
    app: ${app_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${app_name}
  template:
    metadata:
      labels:
        app: ${app_name}
      annotations:
        pra.kedify.io/reconcile: enabled
    spec:
      containers:
        - name: load-generator
          image: ${image}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: BASELINE_CPU_MILLICORES
              value: "100"
            - name: BASELINE_MEMORY_MIB
              value: "96"
            - name: SCHEDULE_JSON
              value: '${schedule_payload}'
          resources:
            requests:
              cpu: 100m
              memory: 96Mi
            limits:
              cpu: 300m
              memory: 600Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ${app_name}${namespace_line}
  labels:
    app: ${app_name}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app: ${app_name}
---
apiVersion: keda.kedify.io/v1alpha1
kind: PodResourceAutoscaler
metadata:
  name: ${app_name}${namespace_line}
spec:
  target:
    kind: deployment
    name: ${app_name}
  containerName: load-generator
  policy:
    pollInterval: 5s
    consecutiveSamples: 2
    cooldown: 30s
    after: containerReady
    delay: 5s
    cpu:
      requests:
        scaleUpThreshold: 75
        scaleDownThreshold: 45
        targetUtilization: 60
      limits:
        scaleUpThreshold: 85
        scaleDownThreshold: 60
        targetUtilization: 70
    memory:
      requests:
        scaleUpThreshold: 75
        scaleDownThreshold: 50
        targetUtilization: 60
      limits:
        scaleUpThreshold: 85
        scaleDownThreshold: 60
        targetUtilization: 70
  bounds:
    cpu:
      requests:
        min: 100m
        max: "2"
        step: 200m
        stepPercent: 50
      limits:
        min: 300m
        max: "3"
        step: 300m
        stepPercent: 50
    memory:
      requests:
        min: 96Mi
        max: 2Gi
        step: 128Mi
        stepPercent: 50
      limits:
        min: 600Mi
        max: 3Gi
        step: 256Mi
        stepPercent: 50
EOF

  if (( i < count )); then
    cat >>"$output" <<EOF
---
EOF
  fi
done

echo "generated ${count} app(s) to ${output}"
