{
 "title": "Podinfo - Vertical Scaling",
 "description": "Grafana Dashboard for Podinfo & vertical scaling.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "go_goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\".*:9898\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (uri) (http_requests_total{instance=~\".*:9898\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (instance) (http_requests_total{instance=~\".*:9898\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "General Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_requests_total{instance=~\".*:9898\"}[2m]))",
     "legendFormat": "request rate"
    }
   ]
  },
  {
   "title": "Network Input",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "rate(net_bytes_recv[2m])", "legendFormat": "net_bytes_recv" },
    {
     "expr": "rate(net_conntrack_listener_conn_accepted_total[2m])",
     "legendFormat": "net_conn_accepted"
    }
   ]
  }
 ]
}