# https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
ui:
  message: "Hello OTel+Vertical Scaling"
  color: "#222222"
  logo: "https://kedify.io/assets/images/logo.svg"

podAnnotations:
  # so that prometheus receiver in OTel collector can discover the pod and scrape metrics from it
  kedify.io/scrape: "true"
  kedify.io/port: "9898"

  # so that kedify agent is able to apply the new resource profile to the pod
  prp.kedify.io/reconcile: "true"
